alias kali-amap='docker run -it --rm -w /data -v $(pwd):/data $KALI_LINUX_IMAGE amap'
alias kali-burpsuite='docker run -it --rm -e DISPLAY -v $HOME/.Xauthority:/root/.Xauthority --net=host $KALI_LINUX_IMAGE java -jar /usr/bin/burpsuite'
alias kali-commix='docker run -it --rm -w /data -v $(pwd):/data $KALI_LINUX_IMAGE commix'
alias kali-dirb='docker run -it --rm -w /data -v $(pwd):/data $KALI_LINUX_IMAGE dirb'
alias kali-dnschef='docker run -it --rm -w /data -v $(pwd):/data --net=host $KALI_LINUX_IMAGE dnschef'
alias kali-dnsenum='docker run -it --rm -w /data -v $(pwd):/data $KALI_LINUX_IMAGE dnsenum'
alias kali-dnsmap='docker run -it --rm -w /data -v $(pwd):/data $KALI_LINUX_IMAGE dnsmap'
alias kali-dnsrecon='docker run -it --rm -w /data -v $(pwd):/data $KALI_LINUX_IMAGE dnsrecon'
alias kali-dnswalk='docker run -it --rm $KALI_LINUX_IMAGE dnswalk'
alias kali-hping3='docker run -it --rm -w /data -v $(pwd):/data $KALI_LINUX_IMAGE hping3'
alias kali-sh='docker run -it --rm --net=host --privileged -e DISPLAY -v $HOME/.Xauthority:/root/.Xauthority $KALI_LINUX_IMAGE /bin/bash'
alias kali-msfconsole='docker run -it --rm --net=host  -v ~/.msf4:/root/.msf4 -v /tmp/msf:/tmp/data $KALI_LINUX_IMAGE msfconsole'
alias kali-msfvenom='docker run -it --rm -w /data -v $(pwd):/data $KALI_LINUX_IMAGE msfvenom'
alias kali-ndiff='docker run -it --rm -w /data -v $(pwd):/data $KALI_LINUX_IMAGE ndiff'
alias kali-netdiscover='docker run -it --rm --net=host -w /data -v $(pwd):/data $KALI_LINUX_IMAGE netdiscover'
alias kali-nikto='docker run -it --rm --net=host -w /data -v $(pwd):/data $KALI_LINUX_IMAGE nikto'
alias kali-nmap='docker run --rm --net=host --privileged $KALI_LINUX_IMAGE nmap'
alias kali-padbuster='docker run -it --rm $KALI_LINUX_IMAGE padbuster'
alias kali-reaver='docker run -it --rm --net=host --privileged -w /data -v $(pwd):/data $KALI_LINUX_IMAGE reaver'
alias kali-responder='docker run -it --rm --net=host $KALI_LINUX_IMAGE responder'
alias kali-searchsploit='docker run --rm $KALI_LINUX_IMAGE searchsploit'
alias kali-sqlmap='docker run -it --rm --net=host -w /data -v ~/.sqlmap:/root/.sqlmap -v $(pwd):/data $KALI_LINUX_IMAGE sqlmap'
alias kali-socat='docker run --rm -w /data -v $(pwd):/data --net=host $KALI_LINUX_IMAGE socat'
alias kali-tshark='docker run --rm -w /data -v $(pwd):/data --net=host --privileged $KALI_LINUX_IMAGE tshark'
alias kali-volafox='docker run -it --rm -w /data -v $(pwd):/data $KALI_LINUX_IMAGE volafox'
alias kali-volatility='docker run -it --rm -w /data -v $(pwd):/data $KALI_LINUX_IMAGE volatility'
alias kali-wash='docker run -it --rm -w /data -v $(pwd):/data --net=host --privileged $KALI_LINUX_IMAGE wash'
alias kali-webscarab='docker run -it --rm -w /data -v $(pwd):/data -e DISPLAY -v $HOME/.Xauthority:/root/.Xauthority --net=host $KALI_LINUX_IMAGE java -jar /usr/bin/webscarab'
alias kali-wireshark='docker run -it --rm -w /data -v $(pwd):/data -e DISPLAY -v $HOME/.Xauthority:/root/.Xauthority --net=host --privileged $KALI_LINUX_IMAGE wireshark'
alias kali-wpscan='docker run -it --rm -w /data -v $(pwd):/data $KALI_LINUX_IMAGE wpscan'
alias kali-yersinia='docker run -it --rm -w /data -v $(pwd):/data $KALI_LINUX_IMAGE yersinia'
alias kali-zaproxy='docker run -it --rm -v ~/.ZAP:/root/.ZAP -e DISPLAY -v $HOME/.Xauthority:/root/.Xauthority --net=host $KALI_LINUX_IMAGE zaproxy'
